### ISSUE TITLE
max_ports_per_vm with dynamic allocation

### ISSUE THREAD

**Issue by ankurgupta-fk** [terraform-google-modules/terraform-google-cloud-nat#123]
### TL;DR

[This](https://github.com/terraform-google-modules/terraform-google-cloud-nat/pull/73) pull request added support for dynamic port allocation, but did not add support for `max_ports_per_vm`

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_router_nat#max_ports_per_vm
```

**Comment by imrannayer** [comment]
Fixed in #124
