### ISSUE TITLE
Leaving nat_ips not defined causes a terraform error on > 0.12 

### ISSUE THREAD

**Issue by AdamClarkRock** [terraform-google-modules/terraform-google-cloud-nat#15]
Running the basic example with Terraform v0.12.5

> module "cloud-nat" {
>   source     = "terraform-google-modules/cloud-nat/google"
>   project_id = "${var.project_id}"
>   region     = "${var.region}"
>   router     = "${var.router_name}"
> }

I see the following error thrown

> Error: Incorrect attribute value type
> 
>   on .terraform/modules/cloud-nat/terraform-google-modules-terraform-google-cloud-nat-137878d/main.tf line 42, in resource "google_compute_router_nat" "main":
>   42:   nat_ips                            = ["${var.nat_ips}"]
> 
> Inappropriate value for attribute "nat_ips": element 0: string required.

**Comment by morgante** [comment]
Terraform 0.12 isn't yet supported for this module, so hopefully once #11 is fixed this will also be fixed.
