### ISSUE TITLE
drain_nat_ips support

### ISSUE THREAD

**Issue by LeandroFPeixoto** [terraform-google-modules/terraform-google-cloud-nat#163]
### TL;DR

Add drain_nat_ips support

variables.tf
![image](https://github.com/user-attachments/assets/7e9e8c8c-c025-461d-a279-5ae958704554)

main.tf
![image](https://github.com/user-attachments/assets/0d95a8c3-6423-4646-bd5c-c35d7cb6ea72)

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_router_nat#drain_nat_ips

https://github.com/hashicorp/terraform-provider-google-beta/blob/main/website/docs/r/compute_router_nat.html.markdown?plain=1#L297
```

**Comment by imrannayer** [comment]
Fixed in #162
