### ISSUE TITLE
Output wait for CloudNAT

### ISSUE THREAD

**Issue by kevensen** [terraform-google-modules/terraform-google-cloud-nat#22]
I would like to set one of the outputs, _region_ for example, to be set only when the CloudNAT is available.  This would help build a dependency chain for resources, such as VM's to only spin up once the CloudNAT is available.  Something like:

```hcl
output "region" {
  description = "Cloud NAT region"
  value       = var.region
  depends_on = [
    google_compute_router_nat.main,
  ]
}

Are there consideration for which I need to account?

**Comment by morgante** [comment]
Instead of using an explicit depends_on, you can use an implicit dependency:

```
output "region" {
  description = "Cloud NAT region"
  value       = google_compute_router_nat.main.region
}
```

**Comment by kevensen** [comment]
SGTM!
