### ISSUE TITLE
Release log_config

### ISSUE THREAD

**Issue by niven01** [terraform-google-modules/terraform-google-cloud-nat#30]
Hello,

Is there a timeline around when the new log_config support will be released? 

Currently I'm using `source = "github.com/terraform-google-modules/terraform-google-cloud-nat"` in order to deploy and use cloud-nat with log_config support

**Comment by morgante** [comment]
Done: https://github.com/terraform-google-modules/terraform-google-cloud-nat/blob/master/CHANGELOG.md#130-2020-03-30
