### ISSUE TITLE
enable_endpoint_independent_mapping attribute not supported by module

### ISSUE THREAD

**Issue by cgsquid** [terraform-google-modules/terraform-google-cloud-nat#43]
The enable_endpoint_independent_mapping argument is not supported in this module, but supported by the underlying [google_compute_router_nat resource](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_router_nat#enable_endpoint_independent_mapping). It would be helpful to be able to pass this argument using cloud-nat module.

**Comment by mark-00** [comment]
I think this is solved in release 3.52.0 
https://github.com/hashicorp/terraform-provider-google/pull/8049

**Comment by mark-00** [comment]
the field is recently added to the google provider in release 3.52.0

**Comment by billyfoss** [comment]
Yes, this will require an update in the required provider version. 
It also requires a small fix to pass the extra parameter through the module.  
I'm not sure if the parameter should default true or null. The provider defaults to true, but if the module defaults to true, it might override any manual value the user set previously.

**Comment by morgante** [comment]
We'd be happy to look at a PR. The default should probably be null.
