### ISSUE TITLE
compute_router_nat subnetwork always changes for LIST_OF_SUBNETWORKS

### ISSUE THREAD

**Issue by gdsotirov** [terraform-google-modules/terraform-google-cloud-nat#51]
I use the module to setup NAT for specific subnetwork like this:

```hcl
module "cloud-nat" {
	source		= "terraform-google-modules/cloud-nat/google"
	version		= "~> 1.4"
	# ... 
	source_subnetwork_ip_ranges_to_nat	= "LIST_OF_SUBNETWORKS"
	subnetworks	=	[{
		name					= "test"
		source_ip_ranges_to_nat	= ["10.10.0.0/24"]
		secondary_ip_range_names= []
		}
	]
}
```

After initial apply on the next plan or apply Terraform always shows a change even though there was no change actually either in the Terraform code or on the resource in GCP manually. This is the plan:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.cloud-nat.google_compute_router_nat.main will be updated in-place
  ~ resource "google_compute_router_nat" "main" {
        id                                  = ".../.../test-router/test-nat-over-test-router"
        name                                = "test-nat-over-test-router"
        # (13 unchanged attributes hidden)

      - subnetwork {
          - name                     = "https://www.googleapis.com/compute/v1/projects/.../regions/.../subnetworks/test" -> null
          - secondary_ip_range_names = [] -> null
          - source_ip_ranges_to_nat  = [
              - "ALL_IP_RANGES",
            ] -> null
        }
      + subnetwork {
          + name                     = "test"
          + secondary_ip_range_names = []
          + source_ip_ranges_to_nat  = [
              + "10.10.0.0/24",
            ]
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

The value that appears changed is `source_ip_ranges_to_nat`, but I'm not sure whether the issue is into the module or the GCP API.

Thank you for looking into this and let me know if more information is needed.

P.S. I have not noticed this behavior with the default value ALL_SUBNETWORKS_ALL_IP_RANGES for `source_subnetwork_ip_ranges_to_nat` argument (see [Inputs](https://github.com/terraform-google-modules/terraform-google-cloud-nat#inputs)).

**Comment by gdsotirov** [comment]
This is really not to be closed. I'm seeing these "changes" on a daily basis when applying and they are simply annoying. Can someone look into it?

**Comment by morgante** [comment]
I recommend switching to the cloud-router module: https://github.com/terraform-google-modules/terraform-google-cloud-router

**Comment by gdsotirov** [comment]
OK @morgante, I'll try it next (working) week and I'll write back whether it solves the problem.

**Comment by gdsotirov** [comment]
Switching to cloud-router module is not the solution for the problem I reported @morgante, so this issue should not be closed IMHO.

**Comment by gdsotirov** [comment]
Well, I decided to rewrite my implementation without any module and the problem immediately become apparent. The resource [google_compute_router_nat](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_router_nat) has block [subnetwork](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_router_nat#subnetwork) that requires argument [source_ip_ranges_to_nat](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_router_nat#source_ip_ranges_to_nat) with the following description:

_(Required) List of options for which source IPs in the subnetwork should have NAT enabled. Supported values include: ALL_IP_RANGES, LIST_OF_SECONDARY_IP_RANGES, PRIMARY_IP_RANGE._

So my error was that I was trying to specify subnetwork's CIDR range (i.e. 10.10.0.0/24) in this argument while it only accepts specific values (i.e. `ALL_IP_RANGES`, `LIST_OF_SECONDARY_IP_RANGES` and `PRIMARY_IP_RANGE`). Cloud-nat module README does not provide information about the possible values of the arguments into its subnetworks block and apparently there is no validation of the passed values, but anyway the problem is resolved now, so let this stay closed for good.

**Comment by morgante** [comment]
@gdsotirov Glad you got it working and apologies for the confusion.
