### ISSUE TITLE
new release / version tag after lint-failing file removed

### ISSUE THREAD

**Issue by davemcphee** [terraform-google-modules/terraform-google-cloud-nat#58]
https://github.com/terraform-google-modules/terraform-google-cloud-nat/pull/53
 removed a python script that was failing lint checks. Could a new release be created that contains this fix? 

We're currently referencing this module by it's latest version tag, `v2.0.0`, but that version fails our lint checkers too due to afore mentioned python script. Could we request a new tag pointing to current master, or any commit after PR 53 merge? 

Thanks!

**Comment by lcarstensen** [comment]
+1

**Comment by davemcphee** [comment]
Oh hey @lcarstensen, it's Alex, forgot to mention that I opened this, argh.
