### ISSUE TITLE
Support Dynamic Port Allocation

### ISSUE THREAD

**Issue by kustodian** [terraform-google-modules/terraform-google-cloud-nat#64]
### TL;DR

Add support for [Cloud Nat Dynamic Port Allocation](https://cloud.google.com/nat/docs/using-nat#set-up-dynamic-port). The feature is currently in Preview.

### Terraform Resources

```markdown
[google_compute_router_nat](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_router_nat)
```

### Detailed design

```markdown
I guess the resource should add support for the two additional parameters: `max_ports_per_vm` and `enable_dynamic_port_allocation`.

Example:

resource "google_compute_router_nat" "nat" {
  name                               = "my-router-nat"
  router                             = google_compute_router.router.name
  region                             = google_compute_router.router.region
  nat_ip_allocate_option             = "AUTO_ONLY"
  source_subnetwork_ip_ranges_to_nat = "ALL_SUBNETWORKS_ALL_IP_RANGES"

  min_ports_per_vm: 32
  max_ports_per_vm: 64000
  enable_dynamic_port_allocation: true
}
```
```


### Additional information

_No response_

**Comment by kustodian** [comment]
This is now GA so it would be awesome if it is supported.

**Comment by qfaure** [comment]
any update on the feature ?

**Comment by hanikesn** [comment]
Depends on https://github.com/hashicorp/terraform-provider-google/issues/11052

**Comment by qfaure** [comment]
@hanikesn  it's now released on the provider google.  https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.22.0

**Comment by KG48037** [comment]
max_ports_per_vm was not included in their latest release

**Comment by billyfoss** [comment]
Please note that by the provider defaulting to false, it will revert DPA that has been enabled by other means.  Previous to 4.22 it was possible to enable DPA and this module would ignore the setting. Now it will revert it.

**Comment by pschmidbauer** [comment]
Thanks for merging this. When will it be released?

**Comment by nikhilmakhijani** [comment]
#73 Added dynamic port feature

**Comment by kustodian** [comment]
Awesome!

**Comment by nikhilmakhijani** [comment]
@bharathkkb can this be merged?

**Comment by leeleelou** [comment]
It looks like the Dynamic Port Mapping was released as a part of v4.0.0. However, this still didn't include the `max_ports_per_vm` key. This is causing Terraform to always see a change in Cloud NAT when dynamic port mapping is enabled.

**Comment by ankurgupta-fk** [comment]
@leeleelou Facing the same issue. Logged https://github.com/terraform-google-modules/terraform-google-cloud-nat/issues/123

**Comment by nikhilmakhijani** [comment]
> @leeleelou Facing the same issue. Logged #123

Raised [PR](https://github.com/terraform-google-modules/terraform-google-cloud-nat/pull/124 ). Let me know your thoughts.
