### ISSUE TITLE
Add support for creating Cloud NATs in multiple regions

### ISSUE THREAD

**Issue by thefirstofthe300** [terraform-google-modules/terraform-google-cloud-nat#8]
Cloud NAT resources can only route traffic originating in the same region as the NAT. We should add support to be able to define multiple Cloud NATs for different regions.

**Comment by aaron-lane** [comment]
@thefirstofthe300 would this differ significantly from invoking the module multiple once for each region?

**Comment by thefirstofthe300** [comment]
To be honest, I can't remember what my use-case was here. I don't think it would differ greatly so let's go ahead and close this.
